In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("data\data.csv")
data.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\lenov\AppData\Local\Temp\ipykernel_9852\2775036306.py:1: SyntaxWarning: invalid escape sequence '\d'
  data = pd.read_csv("data\data.csv")

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2021,...,NaN,NaN,47.80,NaN,49.70,48.7 [47.8-49.7],NaN,NaN,EN,2024-08-01T18:30:00.000Z
1,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2021,...,NaN,NaN,48.45,NaN,50.92,49.6 [48.5-50.9],NaN,NaN,EN,2024-08-01T18:30:00.000Z
2,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2021,...,NaN,NaN,50.49,NaN,52.57,51.5 [50.5-52.6],NaN,NaN,EN,2024-08-01T18:30:00.000Z
3,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,2021,...,NaN,NaN,50.73,NaN,52.82,51.6 [50.7-52.8],NaN,NaN,EN,2024-08-01T18:30:00.000Z
4,WHOSIS_000001,Life expectancy at birth (years),text,EMR,Eastern Mediterranean,Country,SOM,Somalia,Year,2021,...,NaN,NaN,50.62,NaN,53.10,51.7 [50.6-53.1],NaN,NaN,EN,2024-08-01T18:30:00.000Z

In [6]:
data.describe()

,Period,Dim2 type,Dim2,Dim2ValueCode,Dim3 type,Dim3,Dim3ValueCode,DataSourceDimValueCode,DataSource,FactValueNumericPrefix,FactValueNumeric,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,FactValueTranslationID,FactComments
count,24420.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24420.000000,0.0,0.0,24380.000000,0.0,24380.000000,0.0,0.0
mean,2010.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.592633,NaN,NaN,44.206297,NaN,45.010174,NaN,NaN
std,6.344419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.456523,NaN,NaN,26.437750,NaN,26.482528,NaN,NaN
min,2000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.080000,NaN,NaN,8.670000,NaN,9.470000,NaN,NaN
25%,2005.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.770000,NaN,NaN,18.440000,NaN,19.140000,NaN,NaN
50%,2010.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.835000,NaN,NaN,32.515000,NaN,33.235000,NaN,NaN
75%,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.870000,NaN,NaN,71.450000,NaN,72.290000,NaN,NaN
max,2021.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.370000,NaN,NaN,87.320000,NaN,87.420000,NaN,NaN

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24420 entries, 0 to 24419
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   IndicatorCode               24420 non-null  str
 1   Indicator                   24420 non-null  str
 2   ValueType                   24420 non-null  str
 3   ParentLocationCode          24420 non-null  str
 4   ParentLocation              24420 non-null  str
 5   Location type               24420 non-null  str
 6   SpatialDimValueCode         24420 non-null  str
 7   Location                    24420 non-null  str
 8   Period type                 24420 non-null  str
 9   Period                      24420 non-null  int64
 10  IsLatestYear                24420 non-null  bool
 11  Dim1 type                   24420 non-null  str
 12  Dim1                        24420 non-null  str
 13  Dim1ValueCode               24420 non-null  str
 14  Dim2 type                   0 non-null      float64
 15  Dim2                        0 non-null      float64
 16  Dim2ValueCode               0 non-null      float64
 17  Dim3 type                   0 non-null      float64
 18  Dim3                        0 non-null      float64
 19  Dim3ValueCode               0 non-null      float64
 20  DataSourceDimValueCode      0 non-null      float64
 21  DataSource                  0 non-null      float64
 22  FactValueNumericPrefix      0 non-null      float64
 23  FactValueNumeric            24420 non-null  float64
 24  FactValueUoM                0 non-null      float64
 25  FactValueNumericLowPrefix   0 non-null      float64
 26  FactValueNumericLow         24380 non-null  float64
 27  FactValueNumericHighPrefix  0 non-null      float64
 28  FactValueNumericHigh        24380 non-null  float64
 29  Value                       24420 non-null  str
 30  FactValueTranslationID      0 non-null      float64
 31  FactComments                0 non-null      float64
 32  Language                    24420 non-null  str
 33  DateModified                24420 non-null  str
dtypes: bool(1), float64(17), int64(1), str(15)
memory usage: 9.6 MB